import { ArrowLeft, BookOpen, CheckCircle2, ChevronLeft, Layers3, LockKeyhole, PlayCircle, ShieldCheck, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import SiteShell from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

const GRADES = [
  { value: "الأول الإعدادي", short: "01", phase: "إعدادي", description: "بداية قوية مع أساسيات اللغة", color: "bg-[#e6f1ed]", ink: "text-[#26665e]" },
  { value: "الثاني الإعدادي", short: "02", phase: "إعدادي", description: "تثبيت القواعد وبناء الثقة", color: "bg-[#f5eed8]", ink: "text-[#8a6a1d]" },
  { value: "الثالث الإعدادي", short: "03", phase: "إعدادي", description: "استعداد ذكي للمرحلة القادمة", color: "bg-[#e7ecf4]", ink: "text-[#3a5c87]" },
  { value: "الأول الثانوي", short: "01", phase: "ثانوي", description: "قراءة أعمق وتعبير أقوى", color: "bg-[#f2e7e3]", ink: "text-[#965b4d]" },
  { value: "الثاني الثانوي", short: "02", phase: "ثانوي", description: "تدريب على الفهم والتحليل", color: "bg-[#e7eef0]", ink: "text-[#3b6870]" },
  { value: "الثالث الثانوي", short: "03", phase: "ثانوي", description: "مراجعة مركزة نحو التفوق", color: "bg-[#eee8f4]", ink: "text-[#72528f]" },
] as const;

export default function Home() {
  const [selectedGrade, setSelectedGrade] = useState<string>("الكل");
  const [search, setSearch] = useState("");
  const lessonsQuery = trpc.platform.lessons.list.useQuery({});
  const lessons = lessonsQuery.data ?? [];
  const visibleLessons = useMemo(
    () => lessons.filter(lesson => (selectedGrade === "الكل" || lesson.grade === selectedGrade) && (!search.trim() || `${lesson.title} ${lesson.unitTitle}`.toLocaleLowerCase("ar").includes(search.trim().toLocaleLowerCase("ar")))),
    [lessons, selectedGrade, search],
  );

  return (
    <SiteShell>
      <section className="relative isolate overflow-hidden bg-[#153f4a] text-[#f9f4e9]">
        <div className="na-hero-grid absolute inset-0 opacity-40" />
        <div className="absolute -left-20 top-10 h-64 w-64 rounded-full bg-[#54b6a0]/15 blur-3xl" />
        <div className="absolute -right-28 bottom-0 h-72 w-72 rounded-full bg-[#e7bd52]/15 blur-3xl" />
        <div className="container relative grid min-h-[570px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_0.9fr] lg:py-24">
          <div className="max-w-2xl">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-[#d9eee7]"><Sparkles className="h-3.5 w-3.5 text-[#e7bd52]" /> منصة أستاذ اللغة العربية</div>
            <h1 className="na-display max-w-xl text-5xl font-extrabold leading-[1.15] sm:text-6xl lg:text-7xl">العربي مش حفظ،<br /><span className="text-[#e7bd52]">العربي فهم.</span></h1>
            <p className="mt-6 max-w-lg text-base leading-8 text-[#c6dcda] sm:text-lg">مع النجيب، كل حصة لها طريق واضح: شرح مرتب، ملف مفيد، ووصول آمن يناسب كل طالب.</p>
            <div className="mt-9 flex flex-wrap items-center gap-3"><a href="#classes" className="inline-flex items-center gap-2 rounded-full bg-[#e7bd52] px-5 py-3 text-sm font-extrabold text-[#153f4a] shadow-lg shadow-black/10 transition-all hover:-translate-y-1 hover:bg-[#f1ce6d]">استكشف الصفوف <ArrowLeft className="h-4 w-4" /></a><a href="#how-it-works" className="inline-flex items-center gap-2 rounded-full border border-white/20 px-5 py-3 text-sm font-bold text-white transition-colors hover:bg-white/10">كيف تبدأ؟</a></div>
            <div className="mt-12 grid max-w-lg grid-cols-3 gap-4 border-t border-white/10 pt-6"><Stat value="6" label="صفوف دراسية" /><Stat value={String(lessons.length)} label="حصة منشورة" /><Stat value="24/7" label="وصول مرن" /></div>
          </div>
          <div className="relative hidden min-h-[380px] lg:block"><div className="absolute right-12 top-8 h-72 w-72 rounded-[42%_58%_58%_42%/46%_45%_55%_54%] border border-white/10 bg-[#1e5660] shadow-2xl shadow-black/15" /><div className="absolute right-28 top-20 flex h-60 w-60 rotate-3 flex-col justify-between rounded-[2rem] bg-[#f9f4e9] p-7 text-[#153f4a] shadow-2xl shadow-black/20"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e7bd52] text-xl font-black">ن</span><span className="rounded-full bg-[#e7eee8] px-3 py-1 text-[10px] font-extrabold text-[#3d756e]">درس اليوم</span></div><div><p className="text-xs font-bold text-[#70908b]">مدخل إلى البلاغة</p><h2 className="mt-2 text-2xl font-extrabold leading-tight">نقرأ النص<br />بعيون جديدة.</h2></div><div className="flex items-center justify-between border-t border-[#e8dfcb] pt-4 text-xs font-bold text-[#5c706e]"><span className="flex items-center gap-1.5"><PlayCircle className="h-4 w-4 text-[#c39735]" /> فيديو وملف</span><span>النجيب</span></div></div><div className="absolute bottom-9 left-0 rotate-[-7deg] rounded-3xl border border-white/10 bg-[#e7bd52] px-5 py-4 text-[#153f4a] shadow-xl"><p className="text-[10px] font-bold">تعلّم بهدوء</p><p className="mt-1 text-lg font-extrabold">خطوة كل يوم</p></div></div>
        </div>
      </section>

      <section id="classes" className="container scroll-mt-24 py-20 sm:py-24"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-extrabold tracking-[0.2em] text-[#5b9b8d]">اختر مسارك</p><h2 className="na-display text-3xl font-extrabold text-[#153f4a] sm:text-4xl">صفّك الدراسي،<br /><span className="text-[#b08a2d]">بداية حكايتك.</span></h2></div><p className="max-w-sm text-sm leading-7 text-[#69817e]">حصص منظمة حسب الصف والوحدة، لتصل إلى المحتوى الذي تحتاجه من غير تشتت.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{GRADES.map((grade, index) => { const count = lessons.filter(lesson => lesson.grade === grade.value).length; return <button key={grade.value} onClick={() => setSelectedGrade(grade.value)} className={`na-card group rounded-[1.6rem] p-5 text-right transition-all hover:-translate-y-1 hover:shadow-xl ${selectedGrade === grade.value ? "ring-2 ring-[#5b9b8d]" : ""}`}><div className="flex items-start justify-between"><span className={`grid h-12 w-12 place-items-center rounded-2xl text-lg font-extrabold ${grade.color} ${grade.ink}`}>{grade.short}</span><span className="text-xs font-bold text-[#9aa9a4]">0{index + 1}</span></div><p className="mt-6 text-[11px] font-bold text-[#86a09a]">المرحلة {grade.phase}</p><h3 className="mt-1 text-lg font-extrabold text-[#153f4a]">{grade.value}</h3><p className="mt-2 text-xs leading-6 text-[#718580]">{grade.description}</p><div className="mt-5 flex items-center justify-between border-t border-[#ece5d7] pt-4 text-xs font-bold"><span className="text-[#5b9b8d]">{count} حصص متاحة</span><ChevronLeft className="h-4 w-4 text-[#c39735] transition-transform group-hover:-translate-x-1" /></div></button>; })}</div></section>

      <section className="bg-[#f0eadc] py-20 sm:py-24"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-extrabold tracking-[0.2em] text-[#5b9b8d]">المحتوى المنشور</p><h2 className="na-display text-3xl font-extrabold text-[#153f4a]">حصصك في مكان واحد</h2></div><div className="flex gap-2 overflow-auto pb-1 text-xs font-extrabold"><button onClick={() => setSelectedGrade("الكل")} className={`whitespace-nowrap rounded-full px-4 py-2 transition-colors ${selectedGrade === "الكل" ? "bg-[#153f4a] text-white" : "bg-white/60 text-[#68827d] hover:bg-white"}`}>الكل</button>{GRADES.map(grade => <button key={grade.value} onClick={() => setSelectedGrade(grade.value)} className={`whitespace-nowrap rounded-full px-4 py-2 transition-colors ${selectedGrade === grade.value ? "bg-[#153f4a] text-white" : "bg-white/60 text-[#68827d] hover:bg-white"}`}>{grade.value}</button>)}</div></div><div className="mt-6 rounded-2xl bg-white/70 p-3"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث عن الحصة أو الوحدة..." className="h-12 w-full rounded-xl border border-[#e4ddce] bg-white px-4 text-sm outline-none focus:border-[#5b9b8d]" /></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{lessonsQuery.isLoading && <LoadingCard />}{!lessonsQuery.isLoading && visibleLessons.map(lesson => <article key={lesson.id} className="na-card overflow-hidden rounded-[1.6rem] transition-all hover:-translate-y-1 hover:shadow-xl"><div className="flex h-36 items-end justify-between bg-[#1b4d58] p-5 text-white"><div><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold">{lesson.grade}</span><h3 className="mt-3 text-xl font-extrabold">{lesson.title}</h3></div><span className="grid h-11 w-11 place-items-center rounded-full bg-[#e7bd52] text-[#153f4a]"><PlayCircle className="h-5 w-5" /></span></div><div className="p-5"><p className="text-xs font-bold text-[#b08a2d]">{lesson.unitTitle}</p><p className="mt-2 min-h-12 text-sm leading-6 text-[#6d827f]">{lesson.description || "حصة مرتبة بملفاتها وشرحها لتتعلم في وقتك."}</p><div className="mt-5 flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-bold text-[#819590]"><LockKeyhole className="h-4 w-4 text-[#5b9b8d]" /> وصول آمن</span><Link href={`/student/${lesson.id}`} className="inline-flex items-center gap-1 text-xs font-extrabold text-[#153f4a] hover:text-[#b08a2d]">افتح الحصة <ArrowLeft className="h-3.5 w-3.5" /></Link></div></div></article>)}{!lessonsQuery.isLoading && visibleLessons.length === 0 && <div className="na-card col-span-full rounded-[1.6rem] p-9 text-center"><Layers3 className="mx-auto h-9 w-9 text-[#b6c9c2]" /><h3 className="mt-4 font-extrabold text-[#153f4a]">المحتوى قيد التجهيز</h3><p className="mt-2 text-sm text-[#718580]">سيظهر هنا كل درس يضيفه المدرّس للصف المختار.</p></div>}</div></div></section>

      <section id="how-it-works" className="container scroll-mt-24 py-20 sm:py-24"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="mb-3 text-xs font-extrabold tracking-[0.2em] text-[#5b9b8d]">ببساطة</p><h2 className="na-display text-3xl font-extrabold leading-tight text-[#153f4a] sm:text-4xl">ثلاث خطوات،<br />وتبدأ الحصة.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#6d827f]">صممنا الرحلة لتكون واضحة للطالب، ومرنة للمدرّس، وآمنة للمحتوى في كل خطوة.</p></div><div className="grid gap-4 sm:grid-cols-3"><Step number="01" icon={BookOpen} title="اختر صفك" text="حدد الصف والحصة التي تريدها." /><Step number="02" icon={ShieldCheck} title="تحقق من بياناتك" text="اكتب الاسم والرقم الموجودين في الكشف." /><Step number="03" icon={CheckCircle2} title="ابدأ التعلم" text="افتح الفيديو والملفات المصرح بها." /></div></div></section>

      <section id="about" className="border-t border-[#e8dfcb] bg-[#153f4a] py-14 text-white"><div className="container flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-lg font-extrabold">جاهز تبدأ مع النجيب؟</p><p className="mt-1 text-sm text-[#c6dcda]">اختر صفك، والباقي علينا.</p></div><a href="#classes" className="inline-flex w-fit items-center gap-2 rounded-full bg-[#e7bd52] px-5 py-3 text-sm font-extrabold text-[#153f4a]">شاهد الصفوف <ArrowLeft className="h-4 w-4" /></a></div></section>
    </SiteShell>
  );
}

function Stat({ value, label }: { value: string; label: string }) { return <div><p className="text-2xl font-extrabold text-[#e7bd52]">{value}</p><p className="mt-1 text-[10px] font-bold text-[#9bc1ba]">{label}</p></div>; }
function Step({ number, icon: Icon, title, text }: { number: string; icon: typeof BookOpen; title: string; text: string }) { return <div className="na-card rounded-[1.4rem] p-5"><span className="text-xs font-extrabold text-[#b08a2d]">{number}</span><Icon className="mt-7 h-6 w-6 text-[#5b9b8d]" /><h3 className="mt-5 text-sm font-extrabold text-[#153f4a]">{title}</h3><p className="mt-2 text-xs leading-6 text-[#718580]">{text}</p></div>; }
function LoadingCard() { return <div className="na-card h-64 animate-pulse rounded-[1.6rem] bg-white/40" />; }
