import { Check, CheckCircle2, ChevronDown, FileUp, FolderOpen, LayoutDashboard, LogOut, Plus, RefreshCw, ShieldCheck, Video, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import SiteShell from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

const GRADES = ["الأول الإعدادي", "الثاني الإعدادي", "الثالث الإعدادي", "الأول الثانوي", "الثاني الثانوي", "الثالث الثانوي"] as const;

type LessonForm = { title: string; grade: typeof GRADES[number]; unitTitle: string; description: string; externalVideoUrl: string; externalFileUrl: string };
const emptyForm: LessonForm = { title: "", grade: GRADES[0], unitTitle: "", description: "", externalVideoUrl: "", externalFileUrl: "" };

export default function TeacherDashboard() {
  const [, navigate] = useLocation();
  const teacherMe = trpc.platform.teacher.me.useQuery();
  const lessonsQuery = trpc.platform.teacher.lessons.useQuery(undefined, { enabled: teacherMe.data?.authenticated === true });
  const purchasesQuery = trpc.platform.teacher.purchases.useQuery(undefined, { enabled: teacherMe.data?.authenticated === true });
  const homeworkQuery = trpc.platform.teacher.homework.useQuery(undefined, { enabled: teacherMe.data?.authenticated === true });
  const utils = trpc.useUtils();
  const [form, setForm] = useState<LessonForm>(emptyForm);
  const [activeLessonId, setActiveLessonId] = useState<number | null>(null);
  const [section, setSection] = useState<"content" | "orders" | "homework">("content");
  const [isFormOpen, setIsFormOpen] = useState(false);

  useEffect(() => {
    if (!teacherMe.isLoading && !teacherMe.data?.authenticated) navigate("/teacher-login");
  }, [navigate, teacherMe.data?.authenticated, teacherMe.isLoading]);

  const createLesson = trpc.platform.teacher.createLesson.useMutation({
    onSuccess: () => { toast.success("تمت إضافة الحصة"); setForm(emptyForm); setIsFormOpen(false); void utils.platform.teacher.lessons.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const uploadAsset = trpc.platform.teacher.uploadAsset.useMutation({
    onSuccess: () => { toast.success("تم رفع الملف وحمايته"); void utils.platform.teacher.lessons.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const updatePurchase = trpc.platform.teacher.updatePurchase.useMutation({
    onSuccess: () => { toast.success("تم تحديث حالة الطلب"); void utils.platform.teacher.purchases.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const deleteAsset = trpc.platform.teacher.deleteAsset.useMutation({
    onSuccess: () => { toast.success("تم حذف المرجع من الحصة"); void utils.platform.teacher.lessons.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const reviewHomework = trpc.platform.teacher.reviewHomework.useMutation({
    onSuccess: () => { toast.success("تم حفظ مراجعة الواجب"); void utils.platform.teacher.homework.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const logout = trpc.platform.teacher.logout.useMutation({ onSuccess: () => navigate("/") });

  if (teacherMe.isLoading || !teacherMe.data?.authenticated) return <div className="grid min-h-screen place-items-center bg-[#f2eee3] text-sm font-bold text-[#5b9b8d]">جارٍ تجهيز لوحتك...</div>;
  const lessons = lessonsQuery.data ?? [];
  const purchases = purchasesQuery.data ?? [];
  const homework = homeworkQuery.data ?? [];

  return <SiteShell><div className="min-h-[calc(100vh-76px)] bg-[#f2eee3]"><div className="container py-8 sm:py-12"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-extrabold tracking-[0.18em] text-[#5b9b8d]">مساحة المدرّس</p><h1 className="na-display text-3xl font-extrabold text-[#153f4a] sm:text-4xl">لوحتي</h1><p className="mt-2 text-sm text-[#718580]">أهلًا بك، {teacherMe.data.teacherName}. كل شيء مرتب في مكانه.</p></div><div className="flex items-center gap-2"><button onClick={() => { void lessonsQuery.refetch(); void purchasesQuery.refetch(); }} className="grid h-10 w-10 place-items-center rounded-xl bg-white text-[#5b9b8d] shadow-sm transition hover:-translate-y-0.5" aria-label="تحديث البيانات"><RefreshCw className="h-4 w-4" /></button><button onClick={() => logout.mutate()} className="inline-flex items-center gap-2 rounded-xl border border-[#e2d9c9] bg-[#fbfaf5] px-4 py-2.5 text-xs font-extrabold text-[#6f8580] transition hover:border-[#cda83b] hover:text-[#153f4a]"><LogOut className="h-4 w-4" /> خروج</button></div></div>

<div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={LayoutDashboard} label="الحصص" value={String(lessons.length)} /><Metric icon={Video} label="مواد مرفوعة" value={String(lessons.filter(item => item.hasVideo || item.hasFile).length)} /><Metric icon={FolderOpen} label="طلبات معلقة" value={String(purchases.filter(item => item.status === "pending").length)} /></div>

<div className="mt-8 grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="na-card h-fit rounded-[1.4rem] p-3"><button onClick={() => setSection("content")} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-right text-sm font-extrabold transition ${section === "content" ? "bg-[#153f4a] text-white" : "text-[#6b837e] hover:bg-[#eef4ef]"}`}><Video className="h-4 w-4" /> الحصص والمحتوى</button><button onClick={() => setSection("orders")} className={`mt-1 flex w-full items-center gap-3 rounded-xl px-4 py-3 text-right text-sm font-extrabold transition ${section === "orders" ? "bg-[#153f4a] text-white" : "text-[#6b837e] hover:bg-[#eef4ef]"}`}><FolderOpen className="h-4 w-4" /> طلبات الشراء{purchases.filter(item => item.status === "pending").length > 0 && <span className="mr-auto grid h-5 min-w-5 place-items-center rounded-full bg-[#e7bd52] px-1 text-[10px] text-[#153f4a]">{purchases.filter(item => item.status === "pending").length}</span>}</button><button onClick={() => setSection("homework")} className={`mt-1 flex w-full items-center gap-3 rounded-xl px-4 py-3 text-right text-sm font-extrabold transition ${section === "homework" ? "bg-[#153f4a] text-white" : "text-[#6b837e] hover:bg-[#eef4ef]"}`}>الواجبات{homework.filter(item => item.status === "ai_graded" || item.status === "pending").length > 0 && <span className="mr-auto grid h-5 min-w-5 place-items-center rounded-full bg-[#e7bd52] px-1 text-[10px] text-[#153f4a]">{homework.filter(item => item.status === "ai_graded" || item.status === "pending").length}</span>}</button><div className="mt-5 border-t border-[#eee7db] px-4 pt-4 text-[11px] leading-6 text-[#8a9c97]"><ShieldCheck className="mb-2 h-4 w-4 text-[#5b9b8d]" /> الملفات لا تُسلّم إلا بعد تحقق الطالب أو تأكيد الطلب.</div></aside>

<main>{section === "content" ? <ContentSection lessons={lessons} form={form} setForm={setForm} isFormOpen={isFormOpen} setIsFormOpen={setIsFormOpen} activeLessonId={activeLessonId} setActiveLessonId={setActiveLessonId} onCreate={() => createLesson.mutate(form)} isCreating={createLesson.isPending} onUpload={(lessonId, kind, file) => uploadFile(file, lessonId, kind, uploadAsset.mutate)} isUploading={uploadAsset.isPending} onDelete={(lessonId, kind) => { if (window.confirm("هل تريد حذف هذا المرجع من الحصة؟")) deleteAsset.mutate({ lessonId, kind }); }} /> : section === "orders" ? <OrdersSection purchases={purchases} onUpdate={(id, status) => updatePurchase.mutate({ id, status })} isUpdating={updatePurchase.isPending} /> : <HomeworkSection homework={homework} onReview={(id: number, status: "approved" | "rejected", score?: number, teacherNote?: string) => reviewHomework.mutate({ id, status, score, teacherNote })} isReviewing={reviewHomework.isPending} />}</main></div></div></div></SiteShell>;
}

function ContentSection({ lessons, form, setForm, isFormOpen, setIsFormOpen, activeLessonId, setActiveLessonId, onCreate, isCreating, onUpload, isUploading, onDelete }: { lessons: any[]; form: LessonForm; setForm: React.Dispatch<React.SetStateAction<LessonForm>>; isFormOpen: boolean; setIsFormOpen: (value: boolean) => void; activeLessonId: number | null; setActiveLessonId: (value: number | null) => void; onCreate: () => void; isCreating: boolean; onUpload: (lessonId: number, kind: "video" | "file", file: File) => void; isUploading: boolean; onDelete: (lessonId: number, kind: "video" | "file") => void }) {
  return <div><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold text-[#153f4a]">المحتوى التعليمي</h2><p className="mt-1 text-xs text-[#78908a]">أضف حصة جديدة أو أرفق ملفاتها من هنا.</p></div><button onClick={() => setIsFormOpen(!isFormOpen)} className="inline-flex items-center gap-2 rounded-xl bg-[#153f4a] px-4 py-3 text-xs font-extrabold text-white transition hover:bg-[#1e5660]"><Plus className="h-4 w-4" /> حصة جديدة</button></div>{isFormOpen && <div className="na-card mt-5 rounded-[1.4rem] p-5 sm:p-7"><div className="flex items-center justify-between"><h3 className="font-extrabold text-[#153f4a]">بيانات الحصة</h3><button onClick={() => setIsFormOpen(false)} className="text-[#8ba09a]" aria-label="إغلاق"><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="عنوان الحصة"><input value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="مثال: أسلوب الشرط" /></Field><Field label="الصف"><select value={form.grade} onChange={event => setForm({ ...form, grade: event.target.value as LessonForm["grade"] })}>{GRADES.map(grade => <option key={grade}>{grade}</option>)}</select></Field><Field label="الوحدة"><input value={form.unitTitle} onChange={event => setForm({ ...form, unitTitle: event.target.value })} placeholder="مثال: النحو" /></Field><Field label="رابط الفيديو (اختياري)"><input type="url" value={form.externalVideoUrl} onChange={event => setForm({ ...form, externalVideoUrl: event.target.value })} placeholder="https://..." /></Field><Field label="رابط الملف (اختياري)"><input type="url" value={form.externalFileUrl} onChange={event => setForm({ ...form, externalFileUrl: event.target.value })} placeholder="https://..." /></Field><Field label="وصف مختصر"><input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="ما الذي سيتعلمه الطالب؟" /></Field></div><div className="mt-5 flex justify-end"><button onClick={onCreate} disabled={isCreating || !form.title || !form.unitTitle} className="rounded-xl bg-[#e7bd52] px-5 py-3 text-xs font-extrabold text-[#153f4a] disabled:cursor-not-allowed disabled:opacity-50">{isCreating ? "جارٍ الحفظ..." : "حفظ الحصة"}</button></div></div>}
<div className="mt-6 space-y-3">{lessons.map(lesson => <div key={lesson.id} className="na-card rounded-[1.4rem] p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#e7eef0] text-[#3b6870]"><Video className="h-5 w-5" /></span><div className="min-w-0"><h3 className="truncate text-sm font-extrabold text-[#153f4a]">{lesson.title}</h3><p className="mt-1 truncate text-xs text-[#7d918c]">{lesson.grade} · {lesson.unitTitle}</p></div></div><div className="flex items-center gap-2 text-xs font-bold"><span className={`rounded-full px-3 py-1 ${lesson.published ? "bg-[#e7f1ed] text-[#3d756e]" : "bg-[#f3e9e3] text-[#9b6856]"}`}>{lesson.published ? "منشورة" : "مخفية"}</span><button onClick={() => setActiveLessonId(activeLessonId === lesson.id ? null : lesson.id)} className="inline-flex items-center gap-1 rounded-lg border border-[#e7dfd0] px-3 py-2 text-[#627d77]">إدارة <ChevronDown className={`h-3.5 w-3.5 transition-transform ${activeLessonId === lesson.id ? "rotate-180" : ""}`} /></button></div></div>{activeLessonId === lesson.id && <div className="mt-4 grid gap-3 border-t border-[#eee7db] pt-4 sm:grid-cols-2"><UploadBox label="فيديو الحصة" kind="video" lessonId={lesson.id} disabled={isUploading} onUpload={onUpload} /> <UploadBox label="ملف الحصة" kind="file" lessonId={lesson.id} disabled={isUploading} onUpload={onUpload} /> {lesson.hasVideo && <button onClick={() => onDelete(lesson.id, "video")} className="rounded-xl border border-[#ead9d1] px-4 py-3 text-xs font-extrabold text-[#a26d5d]">حذف الفيديو</button>} {lesson.hasFile && <button onClick={() => onDelete(lesson.id, "file")} className="rounded-xl border border-[#ead9d1] px-4 py-3 text-xs font-extrabold text-[#a26d5d]">حذف الملف</button>}</div>}</div>)}{lessons.length === 0 && <div className="na-card rounded-[1.4rem] p-10 text-center"><Video className="mx-auto h-8 w-8 text-[#b6c9c2]" /><p className="mt-3 text-sm font-extrabold text-[#153f4a]">لم تُضف حصص بعد</p><p className="mt-1 text-xs text-[#819590]">ابدأ من زر «حصة جديدة» لإضافة أول درس.</p></div>}</div></div>;
}

function HomeworkSection({ homework, onReview, isReviewing }: { homework: any[]; onReview: (id: number, status: "approved" | "rejected", score?: number, teacherNote?: string) => void; isReviewing: boolean }) {
  return <div><h2 className="text-xl font-extrabold text-[#153f4a]">واجبات الطلاب</h2><p className="mt-1 text-xs text-[#78908a]">التصحيح يتم آليًا بواسطة الذكاء الاصطناعي. هذه الصفحة للمتابعة فقط ولا تحتاج اعتمادًا يدويًا.</p><div className="mt-6 space-y-3">{homework.map(item => <div key={item.id} className="na-card rounded-[1.4rem] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-extrabold text-[#153f4a]">{item.studentName}</h3><span className="rounded-full bg-[#f4efe2] px-2.5 py-1 text-[10px] font-bold text-[#886b29]">{item.status === "approved" ? "معتمد" : item.status === "rejected" ? "مرفوض" : "يحتاج مراجعة"}</span></div><p className="mt-2 text-xs text-[#718580]">{item.phone} · {item.grade} · {item.assignmentTitle}</p><p className="mt-2 text-sm font-extrabold text-[#153f4a]">الدرجة المقترحة: {item.score ?? "—"} / {item.maxScore}</p>{item.feedback && <p className="mt-2 max-w-2xl text-xs leading-6 text-[#718580]">{item.feedback}</p>}{item.imageUrl && <a href={item.imageUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-xs font-extrabold text-[#5b9b8d] underline underline-offset-4">فتح صورة الواجب</a>}</div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-2 rounded-xl bg-[#e7f1ed] px-3 py-2.5 text-xs font-extrabold text-[#3d756e]"><CheckCircle2 className="h-4 w-4" /> تم التصحيح آليًا</span></div></div></div>)}{homework.length === 0 && <div className="na-card rounded-[1.4rem] p-10 text-center"><p className="text-sm font-extrabold text-[#153f4a]">لا توجد واجبات مرفوعة بعد</p></div>}</div></div>;
}

function OrdersSection({ purchases, onUpdate, isUpdating }: { purchases: any[]; onUpdate: (id: number, status: "pending" | "confirmed" | "rejected") => void; isUpdating: boolean }) { return <div><h2 className="text-xl font-extrabold text-[#153f4a]">طلبات الشراء</h2><p className="mt-1 text-xs text-[#78908a]">راجع التحويلات وأكّد الطلبات يدويًا قبل فتح المحتوى.</p><div className="mt-6 space-y-3">{purchases.map(item => <div key={item.id} className="na-card rounded-[1.4rem] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-extrabold text-[#153f4a]">{item.studentName}</h3><span className="rounded-full bg-[#f4efe2] px-2.5 py-1 text-[10px] font-bold text-[#886b29]">{item.amount} جنيه</span></div><p className="mt-2 text-xs text-[#718580]">{item.phone} · {item.grade} · {item.scope === "unit" ? `وحدة: ${item.unitTitle}` : "ملف حصة"}</p><p className="mt-1 text-[11px] text-[#9aa9a4]">كود الطلب: {item.accessCode}</p>{item.proofUrl && <a href={item.proofUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex text-[11px] font-extrabold text-[#5b9b8d] underline underline-offset-4">فتح إثبات التحويل</a>}</div><div className="flex items-center gap-2">{item.status === "pending" ? <><button disabled={isUpdating} onClick={() => onUpdate(item.id, "confirmed")} className="inline-flex items-center gap-1.5 rounded-xl bg-[#3b8f70] px-3 py-2.5 text-xs font-extrabold text-white"><Check className="h-4 w-4" /> تأكيد</button><button disabled={isUpdating} onClick={() => onUpdate(item.id, "rejected")} className="inline-flex items-center gap-1.5 rounded-xl border border-[#ead9d1] px-3 py-2.5 text-xs font-extrabold text-[#a26d5d]"><X className="h-4 w-4" /> رفض</button></> : <span className={`rounded-full px-3 py-2 text-xs font-extrabold ${item.status === "confirmed" ? "bg-[#e7f1ed] text-[#3d756e]" : "bg-[#f4e8e3] text-[#a56c5b]"}`}>{item.status === "confirmed" ? "تم التأكيد" : "مرفوض"}</span>}</div></div></div>)}{purchases.length === 0 && <div className="na-card rounded-[1.4rem] p-10 text-center"><FolderOpen className="mx-auto h-8 w-8 text-[#b6c9c2]" /><p className="mt-3 text-sm font-extrabold text-[#153f4a]">لا توجد طلبات حتى الآن</p></div>}</div></div>; }

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-extrabold text-[#4c6a67]">{label}</span>{children}</label>; }
function Metric({ icon: Icon, label, value }: { icon: typeof LayoutDashboard; label: string; value: string }) { return <div className="na-card flex items-center gap-4 rounded-[1.3rem] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f1ed] text-[#5b9b8d]"><Icon className="h-5 w-5" /></span><div><p className="text-2xl font-extrabold text-[#153f4a]">{value}</p><p className="mt-0.5 text-xs font-bold text-[#7b918c]">{label}</p></div></div>; }
function UploadBox({ label, kind, lessonId, disabled, onUpload }: { label: string; kind: "video" | "file"; lessonId: number; disabled: boolean; onUpload: (lessonId: number, kind: "video" | "file", file: File) => void }) { const inputRef = useRef<HTMLInputElement>(null); return <button type="button" onClick={() => inputRef.current?.click()} className="flex items-center gap-3 rounded-xl border border-dashed border-[#c8d9d2] bg-[#f5faf7] p-4 text-right transition hover:border-[#5b9b8d] hover:bg-[#eef7f2] disabled:opacity-50" disabled={disabled}><input ref={inputRef} type="file" className="hidden" accept={kind === "video" ? "video/mp4,video/webm,video/quicktime" : ".pdf,.zip,image/jpeg,image/png"} onChange={event => { const file = event.target.files?.[0]; if (file) onUpload(lessonId, kind, file); event.currentTarget.value = ""; }} /><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-white text-[#5b9b8d]"><FileUp className="h-4 w-4" /></span><span><span className="block text-xs font-extrabold text-[#3c6861]">{label}</span><span className="mt-1 block text-[10px] text-[#819590]">حتى 30 ميجابايت</span></span></button>; }

function uploadFile(file: File, lessonId: number, kind: "video" | "file", mutate: (input: { lessonId: number; kind: "video" | "file"; name: string; mime: string; dataBase64: string }) => void) { if (file.size > 30 * 1024 * 1024) { toast.error("حجم الملف يتجاوز 30 ميجابايت"); return; } const reader = new FileReader(); reader.onload = () => { const value = String(reader.result); const dataBase64 = value.includes(",") ? value.split(",")[1] : value; if (dataBase64) mutate({ lessonId, kind, name: file.name, mime: file.type || "application/octet-stream", dataBase64 }); }; reader.readAsDataURL(file); }
